name: Lint Scripts

on: [push, pull_request]

jobs:
  lint-scripts:
    name: Lint Build Scripts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout docker-repository
        uses: actions/checkout@v5

      - name: Lint Shell Scripts
        run: make lint-shell-scripts

      - name: Lint Docker Files
        run: make lint-dockerfiles

      - name: Lint Makefiles
        run: make lint-makefiles
